In [ ]:
# 1)	Define the following metrics and perform the following operations

i)	Write a Python program using Python Lists


Matrix A =  [[ 3.7827  3.3454  3.2341]  , [ 2.2122  3.5678  3.9087] , 
[1.1234  2.8934,  5.9087]].

Matrix B =  [[ 3.1234  3.0987  3.1234]  , [ 2.1111  3.2222  3.3333] , 
[1.0987  1.3456,  5.1234]].

Matrix C =  [[ 3.1243  3.0989  3.1256 ]  , [ 2.6721  3.6785  3.9017] , 
[1.1254  2.8956,  5.9187]].'''


In [1]:
# Define matrices using Python lists
A = [[3.7827, 3.3454, 3.2341], [2.2122, 3.5678, 3.9087], [1.1234, 2.8934, 5.9087]]
B = [[3.1234, 3.0987, 3.1234], [2.1111, 3.2222, 3.3333], [1.0987, 1.3456, 5.1234]]
C = [[3.1243, 3.0989, 3.1256], [2.6721, 3.6785, 3.9017], [1.1254, 2.8956, 5.9187]]

# Define addition of matrices
def matrix_addition(X, Y):
    result = [[X[i][j] + Y[i][j] for j in range(len(X[0]))] for i in range(len(X))]
    return result

# Define subtraction of matrices
def matrix_subtraction(X, Y):
    result = [[X[i][j] - Y[i][j] for j in range(len(X[0]))] for i in range(len(X))]
    return result

# Define element-wise multiplication of matrices
def matrix_elementwise_multiplication(X, Y):
    result = [[X[i][j] * Y[i][j] for j in range(len(X[0]))] for i in range(len(X))]
    return result

# Define matrix multiplication
def matrix_multiplication(X, Y):
    result = [[sum(X[i][k] * Y[k][j] for k in range(len(Y))) for j in range(len(Y[0]))] for i in range(len(X))]
    return result

# Perform operations
addition_result = matrix_addition(A, B)
subtraction_result = matrix_subtraction(A, B)
elementwise_multiplication_result = matrix_elementwise_multiplication(A, B)
multiplication_result = matrix_multiplication(A, B)

print("Addition of A and B:")
print(addition_result)

print("\nSubtraction of A and B:")
print(subtraction_result)

print("\nElement-wise multiplication of A and B:")
print(elementwise_multiplication_result)

print("\nMatrix multiplication of A and B:")
print(multiplication_result)


Addition of A and B:
[[6.9061, 6.444100000000001, 6.3575], [4.3233, 6.79, 7.242], [2.2221, 4.239, 11.0321]]

Subtraction of A and B:
[[0.6593, 0.24670000000000014, 0.11070000000000002], [0.10110000000000019, 0.34560000000000013, 0.5754000000000001], [0.024699999999999944, 1.5478000000000003, 0.7852999999999994]]

Element-wise multiplication of A and B:
[[11.814885180000001, 10.36639098, 10.10138794], [4.6701754200000005, 11.49616516, 13.02886971], [1.23427958, 3.89335904, 30.27263358]]

Matrix multiplication of A and B:
[[22.43066479, 26.852805330000002, 39.53569494], [18.73605675, 23.61065602, 38.8279668], [16.10897299, 20.754939779999997, 43.42603136]]


In [ ]:
# ii)	Write a Python program and NumPy

In [3]:
import numpy as np

# Define matrices using NumPy
A = np.array([[3.7827, 3.3454, 3.2341], [2.2122, 3.5678, 3.9087], [1.1234, 2.8934, 5.9087]])
B = np.array([[3.1234, 3.0987, 3.1234], [2.1111, 3.2222, 3.3333], [1.0987, 1.3456, 5.1234]])
C = np.array([[3.1243, 3.0989, 3.1256], [2.6721, 3.6785, 3.9017], [1.1254, 2.8956, 5.9187]])

# Perform matrix operations
addition_result = A + B
subtraction_result = A - B
elementwise_multiplication_result = A * B
multiplication_result = np.dot(A, B)

print("Addition of A and B:")
print(addition_result)

print("\nSubtraction of A and B:")
print(subtraction_result)

print("\nElement-wise multiplication of A and B:")
print(elementwise_multiplication_result)

print("\nMatrix multiplication of A and B:")
print(multiplication_result)


Addition of A and B:
[[ 6.9061  6.4441  6.3575]
 [ 4.3233  6.79    7.242 ]
 [ 2.2221  4.239  11.0321]]

Subtraction of A and B:
[[0.6593 0.2467 0.1107]
 [0.1011 0.3456 0.5754]
 [0.0247 1.5478 0.7853]]

Element-wise multiplication of A and B:
[[11.81488518 10.36639098 10.10138794]
 [ 4.67017542 11.49616516 13.02886971]
 [ 1.23427958  3.89335904 30.27263358]]

Matrix multiplication of A and B:
[[22.43066479 26.85280533 39.53569494]
 [18.73605675 23.61065602 38.8279668 ]
 [16.10897299 20.75493978 43.42603136]]


In [ ]:
2)	Write a Python Program and perform the following operations ?
I.	Create a List {1225, 4986, 6789, 7890, 2345, 6783, 0987, 1234, 8765, 3456}
II.	Iterate using a for loop
III.	Iterate using for loop and range
IV.	List Comprehension
V.	Enumerate
VI.	Iter function and next function
VII.	Map function
VIII.	Using zip
IX.	Using NumPy Module


In [5]:


# I: Create a List
my_list = [1225, 4986, 6789, 7890, 2345, 6783, 987, 1234, 8765, 3456]

# II: Iterate using a for loop
print("Iteration using for loop:")
for num in my_list:
    print(num)

# III: Iterate using for loop and range
print("\nIteration using for loop and range:")
for i in range(len(my_list)):
    print(my_list[i])

# IV: List Comprehension
print("\nList Comprehension:")
comprehension_list = [x**2 for x in my_list]
print(comprehension_list)

# V: Enumerate
print("\nUsing enumerate:")
for i, value in enumerate(my_list):
    print(f"i: {i}, Value: {value}")

# VI: Iter function and next function
print("\nUsing iter and next function:")
iterator_list = iter(my_list)
print(next(iterator_list))  
print(next(iterator_list))  

# VII: Map function 
print("\nUsing map Function")
map_list = list(map(lambda x: x + 68, my_list))
print(map_list)

# VIII: Using zip 
print("\nUsing zip:")
other_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
paired_list = list(zip(my_list, other_list))
print(paired_list)

# IX: Using NumPy module 
import numpy as np
print("\nUsing NumPy module:")
numpy_array = np.array(my_list)
numpy_result = numpy_array + 50
print(numpy_result)


Iteration using for loop:
1225
4986
6789
7890
2345
6783
987
1234
8765
3456

Iteration using for loop and range:
1225
4986
6789
7890
2345
6783
987
1234
8765
3456

List Comprehension:
[1500625, 24860196, 46090521, 62252100, 5499025, 46009089, 974169, 1522756, 76825225, 11943936]

Using enumerate:
i: 0, Value: 1225
i: 1, Value: 4986
i: 2, Value: 6789
i: 3, Value: 7890
i: 4, Value: 2345
i: 5, Value: 6783
i: 6, Value: 987
i: 7, Value: 1234
i: 8, Value: 8765
i: 9, Value: 3456

Using iter and next function:
1225
4986

Using map Function
[1293, 5054, 6857, 7958, 2413, 6851, 1055, 1302, 8833, 3524]

Using zip:
[(1225, 1), (4986, 2), (6789, 3), (7890, 4), (2345, 5), (6783, 6), (987, 7), (1234, 8), (8765, 9), (3456, 10)]

Using NumPy module:
[1275 5036 6839 7940 2395 6833 1037 1284 8815 3506]


In [ ]:
3)	For a List A, B, C, D, E write a python program to compute all the combinations and permutations 

4)	Using the same list use itertools compute permutations and combinations 


In [ ]:
#3

In [27]:
import itertools

# List of items
items = ['A', 'B', 'C', 'D', 'E']

# Compute all permutations
print("Permutations:")
for perm in itertools.permutations(items):
    print(perm)

# Compute all combinations (choose 2, 3, 4, etc. elements)
print("\nCombinations:")
for combo_size in range(1, len(items) + 1):
    print(f"Combinations of {combo_size} items:")
    for combo in itertools.combinations(items, combo_size):
        print(combo)


Permutations:
('A', 'B', 'C', 'D', 'E')
('A', 'B', 'C', 'E', 'D')
('A', 'B', 'D', 'C', 'E')
('A', 'B', 'D', 'E', 'C')
('A', 'B', 'E', 'C', 'D')
('A', 'B', 'E', 'D', 'C')
('A', 'C', 'B', 'D', 'E')
('A', 'C', 'B', 'E', 'D')
('A', 'C', 'D', 'B', 'E')
('A', 'C', 'D', 'E', 'B')
('A', 'C', 'E', 'B', 'D')
('A', 'C', 'E', 'D', 'B')
('A', 'D', 'B', 'C', 'E')
('A', 'D', 'B', 'E', 'C')
('A', 'D', 'C', 'B', 'E')
('A', 'D', 'C', 'E', 'B')
('A', 'D', 'E', 'B', 'C')
('A', 'D', 'E', 'C', 'B')
('A', 'E', 'B', 'C', 'D')
('A', 'E', 'B', 'D', 'C')
('A', 'E', 'C', 'B', 'D')
('A', 'E', 'C', 'D', 'B')
('A', 'E', 'D', 'B', 'C')
('A', 'E', 'D', 'C', 'B')
('B', 'A', 'C', 'D', 'E')
('B', 'A', 'C', 'E', 'D')
('B', 'A', 'D', 'C', 'E')
('B', 'A', 'D', 'E', 'C')
('B', 'A', 'E', 'C', 'D')
('B', 'A', 'E', 'D', 'C')
('B', 'C', 'A', 'D', 'E')
('B', 'C', 'A', 'E', 'D')
('B', 'C', 'D', 'A', 'E')
('B', 'C', 'D', 'E', 'A')
('B', 'C', 'E', 'A', 'D')
('B', 'C', 'E', 'D', 'A')
('B', 'D', 'A', 'C', 'E')
('B', 'D', 'A', 'E', 'C'

In [ ]:
#4

In [29]:
import itertools

# List of items
items = ['A', 'B', 'C', 'D', 'E']

# Compute all permutations
print("Permutations:")
for perm in itertools.permutations(items):
    print(perm)

# Compute all combinations 
print("\nCombinations:")
for combo_size in range(1, len(items) + 1):
    print(f"Combinations of {combo_size} items:")
    for combo in itertools.combinations(items, combo_size):
        print(combo)


Permutations:
('A', 'B', 'C', 'D', 'E')
('A', 'B', 'C', 'E', 'D')
('A', 'B', 'D', 'C', 'E')
('A', 'B', 'D', 'E', 'C')
('A', 'B', 'E', 'C', 'D')
('A', 'B', 'E', 'D', 'C')
('A', 'C', 'B', 'D', 'E')
('A', 'C', 'B', 'E', 'D')
('A', 'C', 'D', 'B', 'E')
('A', 'C', 'D', 'E', 'B')
('A', 'C', 'E', 'B', 'D')
('A', 'C', 'E', 'D', 'B')
('A', 'D', 'B', 'C', 'E')
('A', 'D', 'B', 'E', 'C')
('A', 'D', 'C', 'B', 'E')
('A', 'D', 'C', 'E', 'B')
('A', 'D', 'E', 'B', 'C')
('A', 'D', 'E', 'C', 'B')
('A', 'E', 'B', 'C', 'D')
('A', 'E', 'B', 'D', 'C')
('A', 'E', 'C', 'B', 'D')
('A', 'E', 'C', 'D', 'B')
('A', 'E', 'D', 'B', 'C')
('A', 'E', 'D', 'C', 'B')
('B', 'A', 'C', 'D', 'E')
('B', 'A', 'C', 'E', 'D')
('B', 'A', 'D', 'C', 'E')
('B', 'A', 'D', 'E', 'C')
('B', 'A', 'E', 'C', 'D')
('B', 'A', 'E', 'D', 'C')
('B', 'C', 'A', 'D', 'E')
('B', 'C', 'A', 'E', 'D')
('B', 'C', 'D', 'A', 'E')
('B', 'C', 'D', 'E', 'A')
('B', 'C', 'E', 'A', 'D')
('B', 'C', 'E', 'D', 'A')
('B', 'D', 'A', 'C', 'E')
('B', 'D', 'A', 'E', 'C'